title: Doffewebb 3.0
email: info@dofhiortn.se
description: The home of Dofhiortn
baseurl: /
theme: minima
plugins:
  - jekyll-feed


collections:
  songs:
    output: true
    permalink: /song/:name
    layout: "song"

defaults:
  -
    scope:
      path: ""
      type: "songs" # a collection in your site, in plural form
    values:
      layout: "song"

  - 
    scope:
      path: "assets/img"
    values:
      image: true

facebook: https://www.facebook.com/dofhiortn
instagram: https://www.instagram.com/dofhiortn/

show_excerpts: true
